version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: fraud_detection
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
